// Generated by CIRCT firtool-1.128.0
module Exp2(
  input  [15:0] io_in_0,
                io_in_1,
                io_in_2,
                io_in_3,
                io_in_4,
                io_in_5,
                io_in_6,
                io_in_7,
                io_in_8,
                io_in_9,
                io_in_10,
                io_in_11,
  output [15:0] io_out_0,
                io_out_1,
                io_out_2,
                io_out_3,
                io_out_4,
                io_out_5,
                io_out_6,
                io_out_7,
                io_out_8,
                io_out_9,
                io_out_10,
                io_out_11
);

  wire [9:0]   _GEN = {2'h0, io_in_0[7:0]} + 10'h100;
  wire [270:0] _io_out_0_T_1 = {261'h0, _GEN} << io_in_0[15:8];
  wire [9:0]   _GEN_0 = {2'h0, io_in_1[7:0]} + 10'h100;
  wire [270:0] _io_out_1_T_1 = {261'h0, _GEN_0} << io_in_1[15:8];
  wire [9:0]   _GEN_1 = {2'h0, io_in_2[7:0]} + 10'h100;
  wire [270:0] _io_out_2_T_1 = {261'h0, _GEN_1} << io_in_2[15:8];
  wire [9:0]   _GEN_2 = {2'h0, io_in_3[7:0]} + 10'h100;
  wire [270:0] _io_out_3_T_1 = {261'h0, _GEN_2} << io_in_3[15:8];
  wire [9:0]   _GEN_3 = {2'h0, io_in_4[7:0]} + 10'h100;
  wire [270:0] _io_out_4_T_1 = {261'h0, _GEN_3} << io_in_4[15:8];
  wire [9:0]   _GEN_4 = {2'h0, io_in_5[7:0]} + 10'h100;
  wire [270:0] _io_out_5_T_1 = {261'h0, _GEN_4} << io_in_5[15:8];
  wire [9:0]   _GEN_5 = {2'h0, io_in_6[7:0]} + 10'h100;
  wire [270:0] _io_out_6_T_1 = {261'h0, _GEN_5} << io_in_6[15:8];
  wire [9:0]   _GEN_6 = {2'h0, io_in_7[7:0]} + 10'h100;
  wire [270:0] _io_out_7_T_1 = {261'h0, _GEN_6} << io_in_7[15:8];
  wire [9:0]   _GEN_7 = {2'h0, io_in_8[7:0]} + 10'h100;
  wire [270:0] _io_out_8_T_1 = {261'h0, _GEN_7} << io_in_8[15:8];
  wire [9:0]   _GEN_8 = {2'h0, io_in_9[7:0]} + 10'h100;
  wire [270:0] _io_out_9_T_1 = {261'h0, _GEN_8} << io_in_9[15:8];
  wire [9:0]   _GEN_9 = {2'h0, io_in_10[7:0]} + 10'h100;
  wire [270:0] _io_out_10_T_1 = {261'h0, _GEN_9} << io_in_10[15:8];
  wire [9:0]   _GEN_10 = {2'h0, io_in_11[7:0]} + 10'h100;
  wire [270:0] _io_out_11_T_1 = {261'h0, _GEN_10} << io_in_11[15:8];
  assign io_out_0 =
    $signed(io_in_0[15:8]) > 8'sh0
      ? _io_out_0_T_1[15:0]
      : {6'h0, _GEN} >> 8'h0 - io_in_0[15:8];
  assign io_out_1 =
    $signed(io_in_1[15:8]) > 8'sh0
      ? _io_out_1_T_1[15:0]
      : {6'h0, _GEN_0} >> 8'h0 - io_in_1[15:8];
  assign io_out_2 =
    $signed(io_in_2[15:8]) > 8'sh0
      ? _io_out_2_T_1[15:0]
      : {6'h0, _GEN_1} >> 8'h0 - io_in_2[15:8];
  assign io_out_3 =
    $signed(io_in_3[15:8]) > 8'sh0
      ? _io_out_3_T_1[15:0]
      : {6'h0, _GEN_2} >> 8'h0 - io_in_3[15:8];
  assign io_out_4 =
    $signed(io_in_4[15:8]) > 8'sh0
      ? _io_out_4_T_1[15:0]
      : {6'h0, _GEN_3} >> 8'h0 - io_in_4[15:8];
  assign io_out_5 =
    $signed(io_in_5[15:8]) > 8'sh0
      ? _io_out_5_T_1[15:0]
      : {6'h0, _GEN_4} >> 8'h0 - io_in_5[15:8];
  assign io_out_6 =
    $signed(io_in_6[15:8]) > 8'sh0
      ? _io_out_6_T_1[15:0]
      : {6'h0, _GEN_5} >> 8'h0 - io_in_6[15:8];
  assign io_out_7 =
    $signed(io_in_7[15:8]) > 8'sh0
      ? _io_out_7_T_1[15:0]
      : {6'h0, _GEN_6} >> 8'h0 - io_in_7[15:8];
  assign io_out_8 =
    $signed(io_in_8[15:8]) > 8'sh0
      ? _io_out_8_T_1[15:0]
      : {6'h0, _GEN_7} >> 8'h0 - io_in_8[15:8];
  assign io_out_9 =
    $signed(io_in_9[15:8]) > 8'sh0
      ? _io_out_9_T_1[15:0]
      : {6'h0, _GEN_8} >> 8'h0 - io_in_9[15:8];
  assign io_out_10 =
    $signed(io_in_10[15:8]) > 8'sh0
      ? _io_out_10_T_1[15:0]
      : {6'h0, _GEN_9} >> 8'h0 - io_in_10[15:8];
  assign io_out_11 =
    $signed(io_in_11[15:8]) > 8'sh0
      ? _io_out_11_T_1[15:0]
      : {6'h0, _GEN_10} >> 8'h0 - io_in_11[15:8];
endmodule

