// Generated by CIRCT firtool-1.128.0
module Exp2(
  input  [15:0] io_in_0,
  output [15:0] io_out_0
);

  wire [9:0]   _GEN = {2'h0, io_in_0[7:0]} + 10'h100;
  wire [270:0] _io_out_0_T_2 = {261'h0, _GEN} << io_in_0[15:8];
  assign io_out_0 =
    $signed(io_in_0[15:8]) > 8'sh0 ? _io_out_0_T_2[15:0] : {6'h0, _GEN} >> io_in_0[15:8];
endmodule

