// Generated by CIRCT firtool-1.128.0
module GELU(
  input         clock,
                reset,
  input  [7:0]  io_in_0,
  output [15:0] io_out_0
);

  wire [15:0] _exp2_2_io_out_0;
  wire [15:0] _exp2_1_io_out_0;
  wire [15:0] _log2_io_out_0;
  wire [15:0] xg_0 =
    $signed(io_in_0) > 8'sh0 ? {io_in_0, 8'h0} - 16'h41 : {io_in_0, 8'h0};
  wire [16:0] _xg_mul_const_fullwidth_0_T = {xg_0[15], xg_0} * 17'h1FFFF;
  wire [23:0] _xg_mul_const_fullwidth_0_T_1 =
    {{7{_xg_mul_const_fullwidth_0_T[16]}}, _xg_mul_const_fullwidth_0_T} * 24'h292;
  wire [23:0] res_mul_0 =
    {{8{_exp2_2_io_out_0[15]}}, _exp2_2_io_out_0} * {{8{io_in_0[7]}}, io_in_0, 8'h0};
  Log2 log2 (
    .io_in_0  (_exp2_1_io_out_0 + 16'h100),
    .io_out_0 (_log2_io_out_0)
  );
  Exp2 exp2_1 (
    .clock    (clock),
    .reset    (reset),
    .io_in_0  (_xg_mul_const_fullwidth_0_T_1[23:8]),
    .io_out_0 (_exp2_1_io_out_0)
  );
  Exp2 exp2_2 (
    .clock    (clock),
    .reset    (reset),
    .io_in_0  (16'h0 - _log2_io_out_0),
    .io_out_0 (_exp2_2_io_out_0)
  );
  assign io_out_0 = res_mul_0[23:8];
endmodule

