// Generated by CIRCT firtool-1.128.0
module GELU(
  input        clock,
               reset,
  input  [7:0] io_in_0,
  output [7:0] io_out_0
);

  wire [15:0] _exp2_1_io_out_0;
  wire [7:0]  _log2_io_out_0;
  Log2 log2 (
    .clock    (clock),
    .reset    (reset),
    .io_in_0  (_exp2_1_io_out_0[7:0]),
    .io_out_0 (_log2_io_out_0)
  );
  Exp2 exp2_1 (
    .io_in_0
      (($signed(io_in_0) > 8'sh0 ? {io_in_0, 8'h0} + 16'h3F : {io_in_0, 8'h0}) * 16'h292),
    .io_out_0 (_exp2_1_io_out_0)
  );
  Exp2 exp2_2 (
    .io_in_0  (16'h0 - {{8{_log2_io_out_0[7]}}, _log2_io_out_0}),
    .io_out_0 (/* unused */)
  );
  assign io_out_0 = 8'h0;
endmodule

