// Generated by CIRCT firtool-1.128.0
module Log2(
  input        clock,
               reset,
  input  [7:0] io_in_0,
  output [7:0] io_out_0
);

  wire [7:0]  _leading_one_pos_T_9 = {4'h0, io_in_0[7:4]} | {io_in_0[3:0], 4'h0};
  wire [7:0]  _leading_one_pos_T_19 =
    {2'h0, _leading_one_pos_T_9[7:2] & 6'h33} | {_leading_one_pos_T_9[5:0] & 6'h33, 2'h0};
  wire [6:0]  _leading_one_pos_T_29 =
    _leading_one_pos_T_19[7:1] & 7'h55 | {1'h0, _leading_one_pos_T_19[4:0] & 5'h15, 1'h0};
  wire [3:0]  leading_one_pos =
    4'h8
    - {1'h0,
       _leading_one_pos_T_29[0]
         ? 3'h0
         : _leading_one_pos_T_29[1]
             ? 3'h1
             : _leading_one_pos_T_29[2]
                 ? 3'h2
                 : _leading_one_pos_T_29[3]
                     ? 3'h3
                     : _leading_one_pos_T_29[4]
                         ? 3'h4
                         : _leading_one_pos_T_29[5]
                             ? 3'h5
                             : {2'h3, ~(_leading_one_pos_T_29[6])}};
  wire        x_gt_one = leading_one_pos[3];
  wire [3:0]  w = x_gt_one ? leading_one_pos + 4'h7 : 4'h8 - leading_one_pos - 4'h1;
  wire [22:0] x = x_gt_one ? {15'h0, io_in_0 >> w} : {15'h0, io_in_0} << w;
  assign io_out_0 = x[7:0];
endmodule

