// Generated by CIRCT firtool-1.128.0
module Log2(
  input  [15:0] io_in_0,
                io_in_1,
                io_in_2,
                io_in_3,
                io_in_4,
                io_in_5,
                io_in_6,
                io_in_7,
                io_in_8,
                io_in_9,
                io_in_10,
                io_in_11,
  output [15:0] io_out_0,
                io_out_1,
                io_out_2,
                io_out_3,
                io_out_4,
                io_out_5,
                io_out_6,
                io_out_7,
                io_out_8,
                io_out_9,
                io_out_10,
                io_out_11
);

  wire [15:0] _leading_one_pos_T_9 = {8'h0, io_in_0[15:8]} | {io_in_0[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_19 =
    {4'h0, _leading_one_pos_T_9[15:4] & 12'hF0F}
    | {_leading_one_pos_T_9[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_29 =
    {2'h0, _leading_one_pos_T_19[15:2] & 14'h3333}
    | {_leading_one_pos_T_19[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_39 =
    _leading_one_pos_T_29[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_29[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos =
    4'h0
    - (_leading_one_pos_T_39[0]
         ? 4'h0
         : _leading_one_pos_T_39[1]
             ? 4'h1
             : _leading_one_pos_T_39[2]
                 ? 4'h2
                 : _leading_one_pos_T_39[3]
                     ? 4'h3
                     : _leading_one_pos_T_39[4]
                         ? 4'h4
                         : _leading_one_pos_T_39[5]
                             ? 4'h5
                             : _leading_one_pos_T_39[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_39[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_39[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_39[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_39[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_39[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_39[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_39[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_39[14])});
  wire [3:0]  w =
    leading_one_pos[3] ? leading_one_pos + 4'h7 : 4'h8 - leading_one_pos - 4'h1;
  wire [30:0] _x_T_3 = {15'h0, io_in_0} << w;
  wire [15:0] x = leading_one_pos[3] ? io_in_0 >> w : _x_T_3[15:0];
  wire [15:0] _GEN = {4'h0, w, 8'h0};
  wire [15:0] _leading_one_pos_T_81 = {8'h0, io_in_1[15:8]} | {io_in_1[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_91 =
    {4'h0, _leading_one_pos_T_81[15:4] & 12'hF0F}
    | {_leading_one_pos_T_81[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_101 =
    {2'h0, _leading_one_pos_T_91[15:2] & 14'h3333}
    | {_leading_one_pos_T_91[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_111 =
    _leading_one_pos_T_101[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_101[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_1 =
    4'h0
    - (_leading_one_pos_T_111[0]
         ? 4'h0
         : _leading_one_pos_T_111[1]
             ? 4'h1
             : _leading_one_pos_T_111[2]
                 ? 4'h2
                 : _leading_one_pos_T_111[3]
                     ? 4'h3
                     : _leading_one_pos_T_111[4]
                         ? 4'h4
                         : _leading_one_pos_T_111[5]
                             ? 4'h5
                             : _leading_one_pos_T_111[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_111[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_111[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_111[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_111[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_111[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_111[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_111[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_111[14])});
  wire [3:0]  w_1 =
    leading_one_pos_1[3] ? leading_one_pos_1 + 4'h7 : 4'h8 - leading_one_pos_1 - 4'h1;
  wire [30:0] _x_T_7 = {15'h0, io_in_1} << w_1;
  wire [15:0] x_1 = leading_one_pos_1[3] ? io_in_1 >> w_1 : _x_T_7[15:0];
  wire [15:0] _GEN_0 = {4'h0, w_1, 8'h0};
  wire [15:0] _leading_one_pos_T_153 = {8'h0, io_in_2[15:8]} | {io_in_2[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_163 =
    {4'h0, _leading_one_pos_T_153[15:4] & 12'hF0F}
    | {_leading_one_pos_T_153[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_173 =
    {2'h0, _leading_one_pos_T_163[15:2] & 14'h3333}
    | {_leading_one_pos_T_163[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_183 =
    _leading_one_pos_T_173[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_173[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_2 =
    4'h0
    - (_leading_one_pos_T_183[0]
         ? 4'h0
         : _leading_one_pos_T_183[1]
             ? 4'h1
             : _leading_one_pos_T_183[2]
                 ? 4'h2
                 : _leading_one_pos_T_183[3]
                     ? 4'h3
                     : _leading_one_pos_T_183[4]
                         ? 4'h4
                         : _leading_one_pos_T_183[5]
                             ? 4'h5
                             : _leading_one_pos_T_183[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_183[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_183[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_183[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_183[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_183[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_183[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_183[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_183[14])});
  wire [3:0]  w_2 =
    leading_one_pos_2[3] ? leading_one_pos_2 + 4'h7 : 4'h8 - leading_one_pos_2 - 4'h1;
  wire [30:0] _x_T_11 = {15'h0, io_in_2} << w_2;
  wire [15:0] x_2 = leading_one_pos_2[3] ? io_in_2 >> w_2 : _x_T_11[15:0];
  wire [15:0] _GEN_1 = {4'h0, w_2, 8'h0};
  wire [15:0] _leading_one_pos_T_225 = {8'h0, io_in_3[15:8]} | {io_in_3[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_235 =
    {4'h0, _leading_one_pos_T_225[15:4] & 12'hF0F}
    | {_leading_one_pos_T_225[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_245 =
    {2'h0, _leading_one_pos_T_235[15:2] & 14'h3333}
    | {_leading_one_pos_T_235[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_255 =
    _leading_one_pos_T_245[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_245[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_3 =
    4'h0
    - (_leading_one_pos_T_255[0]
         ? 4'h0
         : _leading_one_pos_T_255[1]
             ? 4'h1
             : _leading_one_pos_T_255[2]
                 ? 4'h2
                 : _leading_one_pos_T_255[3]
                     ? 4'h3
                     : _leading_one_pos_T_255[4]
                         ? 4'h4
                         : _leading_one_pos_T_255[5]
                             ? 4'h5
                             : _leading_one_pos_T_255[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_255[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_255[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_255[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_255[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_255[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_255[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_255[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_255[14])});
  wire [3:0]  w_3 =
    leading_one_pos_3[3] ? leading_one_pos_3 + 4'h7 : 4'h8 - leading_one_pos_3 - 4'h1;
  wire [30:0] _x_T_15 = {15'h0, io_in_3} << w_3;
  wire [15:0] x_3 = leading_one_pos_3[3] ? io_in_3 >> w_3 : _x_T_15[15:0];
  wire [15:0] _GEN_2 = {4'h0, w_3, 8'h0};
  wire [15:0] _leading_one_pos_T_297 = {8'h0, io_in_4[15:8]} | {io_in_4[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_307 =
    {4'h0, _leading_one_pos_T_297[15:4] & 12'hF0F}
    | {_leading_one_pos_T_297[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_317 =
    {2'h0, _leading_one_pos_T_307[15:2] & 14'h3333}
    | {_leading_one_pos_T_307[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_327 =
    _leading_one_pos_T_317[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_317[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_4 =
    4'h0
    - (_leading_one_pos_T_327[0]
         ? 4'h0
         : _leading_one_pos_T_327[1]
             ? 4'h1
             : _leading_one_pos_T_327[2]
                 ? 4'h2
                 : _leading_one_pos_T_327[3]
                     ? 4'h3
                     : _leading_one_pos_T_327[4]
                         ? 4'h4
                         : _leading_one_pos_T_327[5]
                             ? 4'h5
                             : _leading_one_pos_T_327[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_327[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_327[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_327[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_327[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_327[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_327[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_327[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_327[14])});
  wire [3:0]  w_4 =
    leading_one_pos_4[3] ? leading_one_pos_4 + 4'h7 : 4'h8 - leading_one_pos_4 - 4'h1;
  wire [30:0] _x_T_19 = {15'h0, io_in_4} << w_4;
  wire [15:0] x_4 = leading_one_pos_4[3] ? io_in_4 >> w_4 : _x_T_19[15:0];
  wire [15:0] _GEN_3 = {4'h0, w_4, 8'h0};
  wire [15:0] _leading_one_pos_T_369 = {8'h0, io_in_5[15:8]} | {io_in_5[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_379 =
    {4'h0, _leading_one_pos_T_369[15:4] & 12'hF0F}
    | {_leading_one_pos_T_369[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_389 =
    {2'h0, _leading_one_pos_T_379[15:2] & 14'h3333}
    | {_leading_one_pos_T_379[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_399 =
    _leading_one_pos_T_389[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_389[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_5 =
    4'h0
    - (_leading_one_pos_T_399[0]
         ? 4'h0
         : _leading_one_pos_T_399[1]
             ? 4'h1
             : _leading_one_pos_T_399[2]
                 ? 4'h2
                 : _leading_one_pos_T_399[3]
                     ? 4'h3
                     : _leading_one_pos_T_399[4]
                         ? 4'h4
                         : _leading_one_pos_T_399[5]
                             ? 4'h5
                             : _leading_one_pos_T_399[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_399[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_399[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_399[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_399[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_399[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_399[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_399[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_399[14])});
  wire [3:0]  w_5 =
    leading_one_pos_5[3] ? leading_one_pos_5 + 4'h7 : 4'h8 - leading_one_pos_5 - 4'h1;
  wire [30:0] _x_T_23 = {15'h0, io_in_5} << w_5;
  wire [15:0] x_5 = leading_one_pos_5[3] ? io_in_5 >> w_5 : _x_T_23[15:0];
  wire [15:0] _GEN_4 = {4'h0, w_5, 8'h0};
  wire [15:0] _leading_one_pos_T_441 = {8'h0, io_in_6[15:8]} | {io_in_6[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_451 =
    {4'h0, _leading_one_pos_T_441[15:4] & 12'hF0F}
    | {_leading_one_pos_T_441[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_461 =
    {2'h0, _leading_one_pos_T_451[15:2] & 14'h3333}
    | {_leading_one_pos_T_451[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_471 =
    _leading_one_pos_T_461[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_461[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_6 =
    4'h0
    - (_leading_one_pos_T_471[0]
         ? 4'h0
         : _leading_one_pos_T_471[1]
             ? 4'h1
             : _leading_one_pos_T_471[2]
                 ? 4'h2
                 : _leading_one_pos_T_471[3]
                     ? 4'h3
                     : _leading_one_pos_T_471[4]
                         ? 4'h4
                         : _leading_one_pos_T_471[5]
                             ? 4'h5
                             : _leading_one_pos_T_471[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_471[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_471[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_471[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_471[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_471[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_471[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_471[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_471[14])});
  wire [3:0]  w_6 =
    leading_one_pos_6[3] ? leading_one_pos_6 + 4'h7 : 4'h8 - leading_one_pos_6 - 4'h1;
  wire [30:0] _x_T_27 = {15'h0, io_in_6} << w_6;
  wire [15:0] x_6 = leading_one_pos_6[3] ? io_in_6 >> w_6 : _x_T_27[15:0];
  wire [15:0] _GEN_5 = {4'h0, w_6, 8'h0};
  wire [15:0] _leading_one_pos_T_513 = {8'h0, io_in_7[15:8]} | {io_in_7[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_523 =
    {4'h0, _leading_one_pos_T_513[15:4] & 12'hF0F}
    | {_leading_one_pos_T_513[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_533 =
    {2'h0, _leading_one_pos_T_523[15:2] & 14'h3333}
    | {_leading_one_pos_T_523[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_543 =
    _leading_one_pos_T_533[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_533[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_7 =
    4'h0
    - (_leading_one_pos_T_543[0]
         ? 4'h0
         : _leading_one_pos_T_543[1]
             ? 4'h1
             : _leading_one_pos_T_543[2]
                 ? 4'h2
                 : _leading_one_pos_T_543[3]
                     ? 4'h3
                     : _leading_one_pos_T_543[4]
                         ? 4'h4
                         : _leading_one_pos_T_543[5]
                             ? 4'h5
                             : _leading_one_pos_T_543[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_543[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_543[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_543[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_543[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_543[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_543[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_543[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_543[14])});
  wire [3:0]  w_7 =
    leading_one_pos_7[3] ? leading_one_pos_7 + 4'h7 : 4'h8 - leading_one_pos_7 - 4'h1;
  wire [30:0] _x_T_31 = {15'h0, io_in_7} << w_7;
  wire [15:0] x_7 = leading_one_pos_7[3] ? io_in_7 >> w_7 : _x_T_31[15:0];
  wire [15:0] _GEN_6 = {4'h0, w_7, 8'h0};
  wire [15:0] _leading_one_pos_T_585 = {8'h0, io_in_8[15:8]} | {io_in_8[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_595 =
    {4'h0, _leading_one_pos_T_585[15:4] & 12'hF0F}
    | {_leading_one_pos_T_585[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_605 =
    {2'h0, _leading_one_pos_T_595[15:2] & 14'h3333}
    | {_leading_one_pos_T_595[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_615 =
    _leading_one_pos_T_605[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_605[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_8 =
    4'h0
    - (_leading_one_pos_T_615[0]
         ? 4'h0
         : _leading_one_pos_T_615[1]
             ? 4'h1
             : _leading_one_pos_T_615[2]
                 ? 4'h2
                 : _leading_one_pos_T_615[3]
                     ? 4'h3
                     : _leading_one_pos_T_615[4]
                         ? 4'h4
                         : _leading_one_pos_T_615[5]
                             ? 4'h5
                             : _leading_one_pos_T_615[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_615[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_615[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_615[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_615[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_615[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_615[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_615[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_615[14])});
  wire [3:0]  w_8 =
    leading_one_pos_8[3] ? leading_one_pos_8 + 4'h7 : 4'h8 - leading_one_pos_8 - 4'h1;
  wire [30:0] _x_T_35 = {15'h0, io_in_8} << w_8;
  wire [15:0] x_8 = leading_one_pos_8[3] ? io_in_8 >> w_8 : _x_T_35[15:0];
  wire [15:0] _GEN_7 = {4'h0, w_8, 8'h0};
  wire [15:0] _leading_one_pos_T_657 = {8'h0, io_in_9[15:8]} | {io_in_9[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_667 =
    {4'h0, _leading_one_pos_T_657[15:4] & 12'hF0F}
    | {_leading_one_pos_T_657[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_677 =
    {2'h0, _leading_one_pos_T_667[15:2] & 14'h3333}
    | {_leading_one_pos_T_667[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_687 =
    _leading_one_pos_T_677[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_677[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_9 =
    4'h0
    - (_leading_one_pos_T_687[0]
         ? 4'h0
         : _leading_one_pos_T_687[1]
             ? 4'h1
             : _leading_one_pos_T_687[2]
                 ? 4'h2
                 : _leading_one_pos_T_687[3]
                     ? 4'h3
                     : _leading_one_pos_T_687[4]
                         ? 4'h4
                         : _leading_one_pos_T_687[5]
                             ? 4'h5
                             : _leading_one_pos_T_687[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_687[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_687[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_687[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_687[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_687[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_687[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_687[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_687[14])});
  wire [3:0]  w_9 =
    leading_one_pos_9[3] ? leading_one_pos_9 + 4'h7 : 4'h8 - leading_one_pos_9 - 4'h1;
  wire [30:0] _x_T_39 = {15'h0, io_in_9} << w_9;
  wire [15:0] x_9 = leading_one_pos_9[3] ? io_in_9 >> w_9 : _x_T_39[15:0];
  wire [15:0] _GEN_8 = {4'h0, w_9, 8'h0};
  wire [15:0] _leading_one_pos_T_729 = {8'h0, io_in_10[15:8]} | {io_in_10[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_739 =
    {4'h0, _leading_one_pos_T_729[15:4] & 12'hF0F}
    | {_leading_one_pos_T_729[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_749 =
    {2'h0, _leading_one_pos_T_739[15:2] & 14'h3333}
    | {_leading_one_pos_T_739[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_759 =
    _leading_one_pos_T_749[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_749[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_10 =
    4'h0
    - (_leading_one_pos_T_759[0]
         ? 4'h0
         : _leading_one_pos_T_759[1]
             ? 4'h1
             : _leading_one_pos_T_759[2]
                 ? 4'h2
                 : _leading_one_pos_T_759[3]
                     ? 4'h3
                     : _leading_one_pos_T_759[4]
                         ? 4'h4
                         : _leading_one_pos_T_759[5]
                             ? 4'h5
                             : _leading_one_pos_T_759[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_759[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_759[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_759[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_759[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_759[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_759[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_759[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_759[14])});
  wire [3:0]  w_10 =
    leading_one_pos_10[3] ? leading_one_pos_10 + 4'h7 : 4'h8 - leading_one_pos_10 - 4'h1;
  wire [30:0] _x_T_43 = {15'h0, io_in_10} << w_10;
  wire [15:0] x_10 = leading_one_pos_10[3] ? io_in_10 >> w_10 : _x_T_43[15:0];
  wire [15:0] _GEN_9 = {4'h0, w_10, 8'h0};
  wire [15:0] _leading_one_pos_T_801 = {8'h0, io_in_11[15:8]} | {io_in_11[7:0], 8'h0};
  wire [15:0] _leading_one_pos_T_811 =
    {4'h0, _leading_one_pos_T_801[15:4] & 12'hF0F}
    | {_leading_one_pos_T_801[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _leading_one_pos_T_821 =
    {2'h0, _leading_one_pos_T_811[15:2] & 14'h3333}
    | {_leading_one_pos_T_811[13:0] & 14'h3333, 2'h0};
  wire [14:0] _leading_one_pos_T_831 =
    _leading_one_pos_T_821[15:1] & 15'h5555
    | {1'h0, _leading_one_pos_T_821[12:0] & 13'h1555, 1'h0};
  wire [3:0]  leading_one_pos_11 =
    4'h0
    - (_leading_one_pos_T_831[0]
         ? 4'h0
         : _leading_one_pos_T_831[1]
             ? 4'h1
             : _leading_one_pos_T_831[2]
                 ? 4'h2
                 : _leading_one_pos_T_831[3]
                     ? 4'h3
                     : _leading_one_pos_T_831[4]
                         ? 4'h4
                         : _leading_one_pos_T_831[5]
                             ? 4'h5
                             : _leading_one_pos_T_831[6]
                                 ? 4'h6
                                 : _leading_one_pos_T_831[7]
                                     ? 4'h7
                                     : _leading_one_pos_T_831[8]
                                         ? 4'h8
                                         : _leading_one_pos_T_831[9]
                                             ? 4'h9
                                             : _leading_one_pos_T_831[10]
                                                 ? 4'hA
                                                 : _leading_one_pos_T_831[11]
                                                     ? 4'hB
                                                     : _leading_one_pos_T_831[12]
                                                         ? 4'hC
                                                         : _leading_one_pos_T_831[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_leading_one_pos_T_831[14])});
  wire [3:0]  w_11 =
    leading_one_pos_11[3] ? leading_one_pos_11 + 4'h7 : 4'h8 - leading_one_pos_11 - 4'h1;
  wire [30:0] _x_T_47 = {15'h0, io_in_11} << w_11;
  wire [15:0] x_11 = leading_one_pos_11[3] ? io_in_11 >> w_11 : _x_T_47[15:0];
  wire [15:0] _GEN_10 = {4'h0, w_11, 8'h0};
  assign io_out_0 = leading_one_pos[3] ? _GEN + x - 16'h100 : x - _GEN - 16'h100;
  assign io_out_1 =
    leading_one_pos_1[3] ? _GEN_0 + x_1 - 16'h100 : x_1 - _GEN_0 - 16'h100;
  assign io_out_2 =
    leading_one_pos_2[3] ? _GEN_1 + x_2 - 16'h100 : x_2 - _GEN_1 - 16'h100;
  assign io_out_3 =
    leading_one_pos_3[3] ? _GEN_2 + x_3 - 16'h100 : x_3 - _GEN_2 - 16'h100;
  assign io_out_4 =
    leading_one_pos_4[3] ? _GEN_3 + x_4 - 16'h100 : x_4 - _GEN_3 - 16'h100;
  assign io_out_5 =
    leading_one_pos_5[3] ? _GEN_4 + x_5 - 16'h100 : x_5 - _GEN_4 - 16'h100;
  assign io_out_6 =
    leading_one_pos_6[3] ? _GEN_5 + x_6 - 16'h100 : x_6 - _GEN_5 - 16'h100;
  assign io_out_7 =
    leading_one_pos_7[3] ? _GEN_6 + x_7 - 16'h100 : x_7 - _GEN_6 - 16'h100;
  assign io_out_8 =
    leading_one_pos_8[3] ? _GEN_7 + x_8 - 16'h100 : x_8 - _GEN_7 - 16'h100;
  assign io_out_9 =
    leading_one_pos_9[3] ? _GEN_8 + x_9 - 16'h100 : x_9 - _GEN_8 - 16'h100;
  assign io_out_10 =
    leading_one_pos_10[3] ? _GEN_9 + x_10 - 16'h100 : x_10 - _GEN_9 - 16'h100;
  assign io_out_11 =
    leading_one_pos_11[3] ? _GEN_10 + x_11 - 16'h100 : x_11 - _GEN_10 - 16'h100;
endmodule

