// Generated by CIRCT firtool-1.128.0
module SiLU(
  input        clock,
               reset,
  input  [7:0] io_in_0,
               io_in_1,
               io_in_2,
               io_in_3,
               io_in_4,
               io_in_5,
               io_in_6,
               io_in_7,
               io_in_8,
               io_in_9,
               io_in_10,
               io_in_11,
  output [7:0] io_out_0,
               io_out_1,
               io_out_2,
               io_out_3,
               io_out_4,
               io_out_5,
               io_out_6,
               io_out_7,
               io_out_8,
               io_out_9,
               io_out_10,
               io_out_11
);

  wire [15:0] _exp2_2_io_out_0;
  wire [15:0] _exp2_2_io_out_1;
  wire [15:0] _exp2_2_io_out_2;
  wire [15:0] _exp2_2_io_out_3;
  wire [15:0] _exp2_2_io_out_4;
  wire [15:0] _exp2_2_io_out_5;
  wire [15:0] _exp2_2_io_out_6;
  wire [15:0] _exp2_2_io_out_7;
  wire [15:0] _exp2_2_io_out_8;
  wire [15:0] _exp2_2_io_out_9;
  wire [15:0] _exp2_2_io_out_10;
  wire [15:0] _exp2_2_io_out_11;
  wire [15:0] _exp2_1_io_out_0;
  wire [15:0] _exp2_1_io_out_1;
  wire [15:0] _exp2_1_io_out_2;
  wire [15:0] _exp2_1_io_out_3;
  wire [15:0] _exp2_1_io_out_4;
  wire [15:0] _exp2_1_io_out_5;
  wire [15:0] _exp2_1_io_out_6;
  wire [15:0] _exp2_1_io_out_7;
  wire [15:0] _exp2_1_io_out_8;
  wire [15:0] _exp2_1_io_out_9;
  wire [15:0] _exp2_1_io_out_10;
  wire [15:0] _exp2_1_io_out_11;
  wire [15:0] _log2_io_out_0;
  wire [15:0] _log2_io_out_1;
  wire [15:0] _log2_io_out_2;
  wire [15:0] _log2_io_out_3;
  wire [15:0] _log2_io_out_4;
  wire [15:0] _log2_io_out_5;
  wire [15:0] _log2_io_out_6;
  wire [15:0] _log2_io_out_7;
  wire [15:0] _log2_io_out_8;
  wire [15:0] _log2_io_out_9;
  wire [15:0] _log2_io_out_10;
  wire [15:0] _log2_io_out_11;
  wire        isPositive_0 = $signed(io_in_0) > 8'sh0;
  wire [15:0] fixInput_0 = {io_in_0, 8'h0};
  wire        isPositive_1 = $signed(io_in_1) > 8'sh0;
  wire        isPositive_2 = $signed(io_in_2) > 8'sh0;
  wire        isPositive_3 = $signed(io_in_3) > 8'sh0;
  wire        isPositive_4 = $signed(io_in_4) > 8'sh0;
  wire        isPositive_5 = $signed(io_in_5) > 8'sh0;
  wire        isPositive_6 = $signed(io_in_6) > 8'sh0;
  wire        isPositive_7 = $signed(io_in_7) > 8'sh0;
  wire        isPositive_8 = $signed(io_in_8) > 8'sh0;
  wire        isPositive_9 = $signed(io_in_9) > 8'sh0;
  wire        isPositive_10 = $signed(io_in_10) > 8'sh0;
  wire        isPositive_11 = $signed(io_in_11) > 8'sh0;
  wire [15:0] _GEN = {io_in_0, 8'h0};
  wire [15:0] xg_0 = isPositive_0 ? _GEN - 16'h1C : _GEN - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_0_T_4 = {xg_0[15], xg_0} * 17'h1FFFF;
  wire [23:0] _GEN_0 =
    {{7{_xg_mul_const_fullwidth_0_T_4[16]}}, _xg_mul_const_fullwidth_0_T_4};
  wire [23:0] _xg_mul_const_fullwidth_0_T_1 = _GEN_0 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_0_T_5 = _GEN_0 * 24'h16C;
  wire [15:0] xg_mul_const_fixwidth_0 =
    isPositive_0
      ? _xg_mul_const_fullwidth_0_T_1[23:8]
      : _xg_mul_const_fullwidth_0_T_5[23:8];
  wire [15:0] _GEN_1 = {io_in_1, 8'h0};
  wire [15:0] xg_1 = isPositive_1 ? _GEN_1 - 16'h1C : _GEN_1 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_1_T_4 = {xg_1[15], xg_1} * 17'h1FFFF;
  wire [23:0] _GEN_2 =
    {{7{_xg_mul_const_fullwidth_1_T_4[16]}}, _xg_mul_const_fullwidth_1_T_4};
  wire [23:0] _xg_mul_const_fullwidth_1_T_1 = _GEN_2 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_1_T_5 = _GEN_2 * 24'h16C;
  wire [15:0] _GEN_3 = {io_in_2, 8'h0};
  wire [15:0] xg_2 = isPositive_2 ? _GEN_3 - 16'h1C : _GEN_3 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_2_T_4 = {xg_2[15], xg_2} * 17'h1FFFF;
  wire [23:0] _GEN_4 =
    {{7{_xg_mul_const_fullwidth_2_T_4[16]}}, _xg_mul_const_fullwidth_2_T_4};
  wire [23:0] _xg_mul_const_fullwidth_2_T_1 = _GEN_4 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_2_T_5 = _GEN_4 * 24'h16C;
  wire [15:0] _GEN_5 = {io_in_3, 8'h0};
  wire [15:0] xg_3 = isPositive_3 ? _GEN_5 - 16'h1C : _GEN_5 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_3_T_4 = {xg_3[15], xg_3} * 17'h1FFFF;
  wire [23:0] _GEN_6 =
    {{7{_xg_mul_const_fullwidth_3_T_4[16]}}, _xg_mul_const_fullwidth_3_T_4};
  wire [23:0] _xg_mul_const_fullwidth_3_T_1 = _GEN_6 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_3_T_5 = _GEN_6 * 24'h16C;
  wire [15:0] _GEN_7 = {io_in_4, 8'h0};
  wire [15:0] xg_4 = isPositive_4 ? _GEN_7 - 16'h1C : _GEN_7 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_4_T_4 = {xg_4[15], xg_4} * 17'h1FFFF;
  wire [23:0] _GEN_8 =
    {{7{_xg_mul_const_fullwidth_4_T_4[16]}}, _xg_mul_const_fullwidth_4_T_4};
  wire [23:0] _xg_mul_const_fullwidth_4_T_1 = _GEN_8 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_4_T_5 = _GEN_8 * 24'h16C;
  wire [15:0] _GEN_9 = {io_in_5, 8'h0};
  wire [15:0] xg_5 = isPositive_5 ? _GEN_9 - 16'h1C : _GEN_9 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_5_T_4 = {xg_5[15], xg_5} * 17'h1FFFF;
  wire [23:0] _GEN_10 =
    {{7{_xg_mul_const_fullwidth_5_T_4[16]}}, _xg_mul_const_fullwidth_5_T_4};
  wire [23:0] _xg_mul_const_fullwidth_5_T_1 = _GEN_10 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_5_T_5 = _GEN_10 * 24'h16C;
  wire [15:0] _GEN_11 = {io_in_6, 8'h0};
  wire [15:0] xg_6 = isPositive_6 ? _GEN_11 - 16'h1C : _GEN_11 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_6_T_4 = {xg_6[15], xg_6} * 17'h1FFFF;
  wire [23:0] _GEN_12 =
    {{7{_xg_mul_const_fullwidth_6_T_4[16]}}, _xg_mul_const_fullwidth_6_T_4};
  wire [23:0] _xg_mul_const_fullwidth_6_T_1 = _GEN_12 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_6_T_5 = _GEN_12 * 24'h16C;
  wire [15:0] _GEN_13 = {io_in_7, 8'h0};
  wire [15:0] xg_7 = isPositive_7 ? _GEN_13 - 16'h1C : _GEN_13 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_7_T_4 = {xg_7[15], xg_7} * 17'h1FFFF;
  wire [23:0] _GEN_14 =
    {{7{_xg_mul_const_fullwidth_7_T_4[16]}}, _xg_mul_const_fullwidth_7_T_4};
  wire [23:0] _xg_mul_const_fullwidth_7_T_1 = _GEN_14 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_7_T_5 = _GEN_14 * 24'h16C;
  wire [15:0] _GEN_15 = {io_in_8, 8'h0};
  wire [15:0] xg_8 = isPositive_8 ? _GEN_15 - 16'h1C : _GEN_15 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_8_T_4 = {xg_8[15], xg_8} * 17'h1FFFF;
  wire [23:0] _GEN_16 =
    {{7{_xg_mul_const_fullwidth_8_T_4[16]}}, _xg_mul_const_fullwidth_8_T_4};
  wire [23:0] _xg_mul_const_fullwidth_8_T_1 = _GEN_16 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_8_T_5 = _GEN_16 * 24'h16C;
  wire [15:0] _GEN_17 = {io_in_9, 8'h0};
  wire [15:0] xg_9 = isPositive_9 ? _GEN_17 - 16'h1C : _GEN_17 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_9_T_4 = {xg_9[15], xg_9} * 17'h1FFFF;
  wire [23:0] _GEN_18 =
    {{7{_xg_mul_const_fullwidth_9_T_4[16]}}, _xg_mul_const_fullwidth_9_T_4};
  wire [23:0] _xg_mul_const_fullwidth_9_T_1 = _GEN_18 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_9_T_5 = _GEN_18 * 24'h16C;
  wire [15:0] _GEN_19 = {io_in_10, 8'h0};
  wire [15:0] xg_10 = isPositive_10 ? _GEN_19 - 16'h1C : _GEN_19 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_10_T_4 = {xg_10[15], xg_10} * 17'h1FFFF;
  wire [23:0] _GEN_20 =
    {{7{_xg_mul_const_fullwidth_10_T_4[16]}}, _xg_mul_const_fullwidth_10_T_4};
  wire [23:0] _xg_mul_const_fullwidth_10_T_1 = _GEN_20 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_10_T_5 = _GEN_20 * 24'h16C;
  wire [15:0] _GEN_21 = {io_in_11, 8'h0};
  wire [15:0] xg_11 = isPositive_11 ? _GEN_21 - 16'h1C : _GEN_21 - 16'h1C;
  wire [16:0] _xg_mul_const_fullwidth_11_T_4 = {xg_11[15], xg_11} * 17'h1FFFF;
  wire [23:0] _GEN_22 =
    {{7{_xg_mul_const_fullwidth_11_T_4[16]}}, _xg_mul_const_fullwidth_11_T_4};
  wire [23:0] _xg_mul_const_fullwidth_11_T_1 = _GEN_22 * 24'h10C;
  wire [23:0] _xg_mul_const_fullwidth_11_T_5 = _GEN_22 * 24'h16C;
  wire [15:0] axg_0 = _exp2_1_io_out_0 + 16'h100;
  wire [15:0] xg_hat_0 = 16'h0 - _log2_io_out_0;
  wire [23:0] res_mul_0 =
    {{8{_exp2_2_io_out_0[15]}}, _exp2_2_io_out_0} * {{8{io_in_0[7]}}, io_in_0, 8'h0};
  wire [23:0] res_mul_1 =
    {{8{_exp2_2_io_out_1[15]}}, _exp2_2_io_out_1} * {{8{io_in_1[7]}}, io_in_1, 8'h0};
  wire [23:0] res_mul_2 =
    {{8{_exp2_2_io_out_2[15]}}, _exp2_2_io_out_2} * {{8{io_in_2[7]}}, io_in_2, 8'h0};
  wire [23:0] res_mul_3 =
    {{8{_exp2_2_io_out_3[15]}}, _exp2_2_io_out_3} * {{8{io_in_3[7]}}, io_in_3, 8'h0};
  wire [23:0] res_mul_4 =
    {{8{_exp2_2_io_out_4[15]}}, _exp2_2_io_out_4} * {{8{io_in_4[7]}}, io_in_4, 8'h0};
  wire [23:0] res_mul_5 =
    {{8{_exp2_2_io_out_5[15]}}, _exp2_2_io_out_5} * {{8{io_in_5[7]}}, io_in_5, 8'h0};
  wire [23:0] res_mul_6 =
    {{8{_exp2_2_io_out_6[15]}}, _exp2_2_io_out_6} * {{8{io_in_6[7]}}, io_in_6, 8'h0};
  wire [23:0] res_mul_7 =
    {{8{_exp2_2_io_out_7[15]}}, _exp2_2_io_out_7} * {{8{io_in_7[7]}}, io_in_7, 8'h0};
  wire [23:0] res_mul_8 =
    {{8{_exp2_2_io_out_8[15]}}, _exp2_2_io_out_8} * {{8{io_in_8[7]}}, io_in_8, 8'h0};
  wire [23:0] res_mul_9 =
    {{8{_exp2_2_io_out_9[15]}}, _exp2_2_io_out_9} * {{8{io_in_9[7]}}, io_in_9, 8'h0};
  wire [23:0] res_mul_10 =
    {{8{_exp2_2_io_out_10[15]}}, _exp2_2_io_out_10} * {{8{io_in_10[7]}}, io_in_10, 8'h0};
  wire [23:0] res_mul_11 =
    {{8{_exp2_2_io_out_11[15]}}, _exp2_2_io_out_11} * {{8{io_in_11[7]}}, io_in_11, 8'h0};
  wire [15:0] _y_round_T = res_mul_0[23:8] + 16'h80;
  wire [7:0]  io_out_0_0 = _y_round_T[15:8];
  wire [15:0] _y_round_T_2 = res_mul_1[23:8] + 16'h80;
  wire [15:0] _y_round_T_4 = res_mul_2[23:8] + 16'h80;
  wire [15:0] _y_round_T_6 = res_mul_3[23:8] + 16'h80;
  wire [15:0] _y_round_T_8 = res_mul_4[23:8] + 16'h80;
  wire [15:0] _y_round_T_10 = res_mul_5[23:8] + 16'h80;
  wire [15:0] _y_round_T_12 = res_mul_6[23:8] + 16'h80;
  wire [15:0] _y_round_T_14 = res_mul_7[23:8] + 16'h80;
  wire [15:0] _y_round_T_16 = res_mul_8[23:8] + 16'h80;
  wire [15:0] _y_round_T_18 = res_mul_9[23:8] + 16'h80;
  wire [15:0] _y_round_T_20 = res_mul_10[23:8] + 16'h80;
  wire [15:0] _y_round_T_22 = res_mul_11[23:8] + 16'h80;
  Log2 log2 (
    .io_in_0   (axg_0),
    .io_in_1   (_exp2_1_io_out_1 + 16'h100),
    .io_in_2   (_exp2_1_io_out_2 + 16'h100),
    .io_in_3   (_exp2_1_io_out_3 + 16'h100),
    .io_in_4   (_exp2_1_io_out_4 + 16'h100),
    .io_in_5   (_exp2_1_io_out_5 + 16'h100),
    .io_in_6   (_exp2_1_io_out_6 + 16'h100),
    .io_in_7   (_exp2_1_io_out_7 + 16'h100),
    .io_in_8   (_exp2_1_io_out_8 + 16'h100),
    .io_in_9   (_exp2_1_io_out_9 + 16'h100),
    .io_in_10  (_exp2_1_io_out_10 + 16'h100),
    .io_in_11  (_exp2_1_io_out_11 + 16'h100),
    .io_out_0  (_log2_io_out_0),
    .io_out_1  (_log2_io_out_1),
    .io_out_2  (_log2_io_out_2),
    .io_out_3  (_log2_io_out_3),
    .io_out_4  (_log2_io_out_4),
    .io_out_5  (_log2_io_out_5),
    .io_out_6  (_log2_io_out_6),
    .io_out_7  (_log2_io_out_7),
    .io_out_8  (_log2_io_out_8),
    .io_out_9  (_log2_io_out_9),
    .io_out_10 (_log2_io_out_10),
    .io_out_11 (_log2_io_out_11)
  );
  wire [15:0] log2_io_out_0;
  assign log2_io_out_0 = _log2_io_out_0;
  Exp2 exp2_1 (
    .io_in_0   (xg_mul_const_fixwidth_0),
    .io_in_1
      (isPositive_1
         ? _xg_mul_const_fullwidth_1_T_1[23:8]
         : _xg_mul_const_fullwidth_1_T_5[23:8]),
    .io_in_2
      (isPositive_2
         ? _xg_mul_const_fullwidth_2_T_1[23:8]
         : _xg_mul_const_fullwidth_2_T_5[23:8]),
    .io_in_3
      (isPositive_3
         ? _xg_mul_const_fullwidth_3_T_1[23:8]
         : _xg_mul_const_fullwidth_3_T_5[23:8]),
    .io_in_4
      (isPositive_4
         ? _xg_mul_const_fullwidth_4_T_1[23:8]
         : _xg_mul_const_fullwidth_4_T_5[23:8]),
    .io_in_5
      (isPositive_5
         ? _xg_mul_const_fullwidth_5_T_1[23:8]
         : _xg_mul_const_fullwidth_5_T_5[23:8]),
    .io_in_6
      (isPositive_6
         ? _xg_mul_const_fullwidth_6_T_1[23:8]
         : _xg_mul_const_fullwidth_6_T_5[23:8]),
    .io_in_7
      (isPositive_7
         ? _xg_mul_const_fullwidth_7_T_1[23:8]
         : _xg_mul_const_fullwidth_7_T_5[23:8]),
    .io_in_8
      (isPositive_8
         ? _xg_mul_const_fullwidth_8_T_1[23:8]
         : _xg_mul_const_fullwidth_8_T_5[23:8]),
    .io_in_9
      (isPositive_9
         ? _xg_mul_const_fullwidth_9_T_1[23:8]
         : _xg_mul_const_fullwidth_9_T_5[23:8]),
    .io_in_10
      (isPositive_10
         ? _xg_mul_const_fullwidth_10_T_1[23:8]
         : _xg_mul_const_fullwidth_10_T_5[23:8]),
    .io_in_11
      (isPositive_11
         ? _xg_mul_const_fullwidth_11_T_1[23:8]
         : _xg_mul_const_fullwidth_11_T_5[23:8]),
    .io_out_0  (_exp2_1_io_out_0),
    .io_out_1  (_exp2_1_io_out_1),
    .io_out_2  (_exp2_1_io_out_2),
    .io_out_3  (_exp2_1_io_out_3),
    .io_out_4  (_exp2_1_io_out_4),
    .io_out_5  (_exp2_1_io_out_5),
    .io_out_6  (_exp2_1_io_out_6),
    .io_out_7  (_exp2_1_io_out_7),
    .io_out_8  (_exp2_1_io_out_8),
    .io_out_9  (_exp2_1_io_out_9),
    .io_out_10 (_exp2_1_io_out_10),
    .io_out_11 (_exp2_1_io_out_11)
  );
  wire [15:0] exp2_1_io_out_0;
  assign exp2_1_io_out_0 = _exp2_1_io_out_0;
  Exp2 exp2_2 (
    .io_in_0   (xg_hat_0),
    .io_in_1   (16'h0 - _log2_io_out_1),
    .io_in_2   (16'h0 - _log2_io_out_2),
    .io_in_3   (16'h0 - _log2_io_out_3),
    .io_in_4   (16'h0 - _log2_io_out_4),
    .io_in_5   (16'h0 - _log2_io_out_5),
    .io_in_6   (16'h0 - _log2_io_out_6),
    .io_in_7   (16'h0 - _log2_io_out_7),
    .io_in_8   (16'h0 - _log2_io_out_8),
    .io_in_9   (16'h0 - _log2_io_out_9),
    .io_in_10  (16'h0 - _log2_io_out_10),
    .io_in_11  (16'h0 - _log2_io_out_11),
    .io_out_0  (_exp2_2_io_out_0),
    .io_out_1  (_exp2_2_io_out_1),
    .io_out_2  (_exp2_2_io_out_2),
    .io_out_3  (_exp2_2_io_out_3),
    .io_out_4  (_exp2_2_io_out_4),
    .io_out_5  (_exp2_2_io_out_5),
    .io_out_6  (_exp2_2_io_out_6),
    .io_out_7  (_exp2_2_io_out_7),
    .io_out_8  (_exp2_2_io_out_8),
    .io_out_9  (_exp2_2_io_out_9),
    .io_out_10 (_exp2_2_io_out_10),
    .io_out_11 (_exp2_2_io_out_11)
  );
  wire [15:0] exp2_2_io_out_0;
  assign exp2_2_io_out_0 = _exp2_2_io_out_0;
  assign io_out_0 = io_out_0_0;
  assign io_out_1 = _y_round_T_2[15:8];
  assign io_out_2 = _y_round_T_4[15:8];
  assign io_out_3 = _y_round_T_6[15:8];
  assign io_out_4 = _y_round_T_8[15:8];
  assign io_out_5 = _y_round_T_10[15:8];
  assign io_out_6 = _y_round_T_12[15:8];
  assign io_out_7 = _y_round_T_14[15:8];
  assign io_out_8 = _y_round_T_16[15:8];
  assign io_out_9 = _y_round_T_18[15:8];
  assign io_out_10 = _y_round_T_20[15:8];
  assign io_out_11 = _y_round_T_22[15:8];
endmodule

