// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module Exp2_Verification();
  `ifndef SYNTHESIS
    always @(posedge Exp2.clock) begin
      if ((`PRINTF_COND_) & ~Exp2.reset)
        $fwrite(32'h80000002, "[EXP2] i=0 in=%b u=%b v=%b one_plus_v=%b isPositive=%d\n",
                $signed(Exp2.io_in_0), $signed(Exp2.u), {8'h0, Exp2._layer_probe},
                Exp2.one_plus_v, Exp2.isPositive);
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

