// Generated by CIRCT firtool-1.128.0
`ifndef layers_QKVLinear_Verification	// src/main/scala/QKVLinear/QKVLinear.scala:16:7
  `define layers_QKVLinear_Verification
  `include "layers-LoadWeight-Verification.sv"	// src/main/scala/QKVLinear/QKVLinear.scala:16:7
`endif // not def layers_QKVLinear_Verification

