// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_1_Verification	// src/main/scala/OutLinear/WeightMem.scala:8:7
  `define layers_WeightMem_1_Verification
  bind WeightMem_1 WeightMem_1_Verification verification ();
`endif // not def layers_WeightMem_1_Verification

