// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_2_Verification	// src/main/scala/FFNUp/WeightMem.scala:8:7
  `define layers_WeightMem_2_Verification
  bind WeightMem_2 WeightMem_2_Verification verification ();
`endif // not def layers_WeightMem_2_Verification

