// Generated by CIRCT firtool-1.128.0
`ifndef layers_LoadWeight_2_Verification	// src/main/scala/FFNUp/LoadW.scala:7:7
  `define layers_LoadWeight_2_Verification
  `include "layers-WeightMem_2-Verification.sv"	// src/main/scala/FFNUp/LoadW.scala:7:7
`endif // not def layers_LoadWeight_2_Verification

