// Generated by CIRCT firtool-1.128.0
`ifndef layers_FFNDownFP32_Verification	// src/main/scala/FFNDown/FFNDownFP32.scala:9:7
  `define layers_FFNDownFP32_Verification
  `include "layers-LoadWeight_3-Verification.sv"	// src/main/scala/FFNDown/FFNDownFP32.scala:9:7
`endif // not def layers_FFNDownFP32_Verification

