// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_Verification	// src/main/scala/QKVLinear/WeightMem.scala:12:7
  `define layers_WeightMem_Verification
  bind WeightMem WeightMem_Verification verification ();
`endif // not def layers_WeightMem_Verification

