// Generated by CIRCT firtool-1.128.0
`ifndef layers_LoadWeight_4_Verification	// src/main/scala/FFNDown/LoadW.scala:7:7
  `define layers_LoadWeight_4_Verification
  `include "layers-WeightMem_3-Verification.sv"	// src/main/scala/FFNDown/LoadW.scala:7:7
`endif // not def layers_LoadWeight_4_Verification

