// Generated by CIRCT firtool-1.128.0
`ifndef layers_FFNUp_Verification	// src/main/scala/FFNUp/FFNUp.scala:16:7
  `define layers_FFNUp_Verification
  `include "layers-LoadWeight_2-Verification.sv"	// src/main/scala/FFNUp/FFNUp.scala:16:7
`endif // not def layers_FFNUp_Verification

