// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_3_Verification	// src/main/scala/FFNDown/WeightMem.scala:8:7
  `define layers_WeightMem_3_Verification
  bind WeightMem_3 WeightMem_3_Verification verification ();
`endif // not def layers_WeightMem_3_Verification

