// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module Log2_Verification();
  `ifndef SYNTHESIS
    always @(posedge Log2.clock) begin
      if ((`PRINTF_COND_) & ~Log2.reset)
        $fwrite(32'h80000002,
                "[LOG2] i=0 in=%b leading_one_pos=%d x_gt_one=%d w=%d x=%b\n",
                $signed(Log2.io_in_0), Log2.leading_one_pos, Log2.x_gt_one, Log2.w,
                Log2.x);
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

