// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module SiLU_Verification();
  `ifndef SYNTHESIS
    always @(posedge SiLU.clock) begin
      if ((`PRINTF_COND_) & ~SiLU.reset)
        $fwrite(32'h80000002,
                "\n    [SiLU]\n    in           = %b\n    fixInput     = %b\n    isPositive   = %d\n    beta_plus    = %b\n    xg           = %b\n    xg_mul_const_fixwidth = %b\n    exg          = %b\n    axg          = %b\n    lxg          = %b\n    xg_hat       = %b\n    sigma_opt    = %b\n    out          = %b\n    ",
                $signed(SiLU.io_in_0), $signed(SiLU.fixInput_0), SiLU.isPositive_0,
                $signed(16'h1C), $signed(SiLU.xg_0),
                $signed(SiLU.xg_mul_const_fixwidth_0), $signed(SiLU.exp2_1_io_out_0),
                $signed(SiLU.axg_0), $signed(SiLU.log2_io_out_0), $signed(SiLU.xg_hat_0),
                $signed(SiLU.exp2_2_io_out_0), $signed(SiLU.io_out_0_0));
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

