// Generated by CIRCT firtool-1.128.0
`ifndef layers_FFNUp_Verification_Assert	// src/main/scala/FFNUp/FFNUp.scala:16:7
  `define layers_FFNUp_Verification_Assert
  `include "layers-FFNUp-Verification.sv"	// src/main/scala/FFNUp/FFNUp.scala:16:7
  `include "layers-LoadWeight_2-Verification-Assert.sv"	// src/main/scala/FFNUp/FFNUp.scala:16:7
`endif // not def layers_FFNUp_Verification_Assert

