// Generated by CIRCT firtool-1.128.0
`ifndef layers_LoadWeight_1_Verification_Assert	// src/main/scala/OutLinear/LoadW.scala:7:7
  `define layers_LoadWeight_1_Verification_Assert
  `include "layers-LoadWeight_1-Verification.sv"	// src/main/scala/OutLinear/LoadW.scala:7:7
  `include "layers-WeightMem_1-Verification-Assert.sv"	// src/main/scala/OutLinear/LoadW.scala:7:7
`endif // not def layers_LoadWeight_1_Verification_Assert

