// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_3_Verification_Assert	// src/main/scala/FFNDown/WeightMem.scala:8:7
  `define layers_WeightMem_3_Verification_Assert
  `include "layers-WeightMem_3-Verification.sv"	// src/main/scala/FFNDown/WeightMem.scala:8:7
  bind WeightMem_3 WeightMem_3_Verification_Assert verification_assert ();
`endif // not def layers_WeightMem_3_Verification_Assert

