// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_2_Verification_Assert	// src/main/scala/FFNUp/WeightMem.scala:8:7
  `define layers_WeightMem_2_Verification_Assert
  `include "layers-WeightMem_2-Verification.sv"	// src/main/scala/FFNUp/WeightMem.scala:8:7
  bind WeightMem_2 WeightMem_2_Verification_Assert verification_assert ();
`endif // not def layers_WeightMem_2_Verification_Assert

