// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_Verification_Assert	// src/main/scala/QKVLinear/WeightMem.scala:12:7
  `define layers_WeightMem_Verification_Assert
  `include "layers-WeightMem-Verification.sv"	// src/main/scala/QKVLinear/WeightMem.scala:12:7
  bind WeightMem WeightMem_Verification_Assert verification_assert ();
`endif // not def layers_WeightMem_Verification_Assert

