// Generated by CIRCT firtool-1.128.0
`ifndef layers_QKVLinear_Verification_Assert	// src/main/scala/QKVLinear/QKVLinear.scala:16:7
  `define layers_QKVLinear_Verification_Assert
  `include "layers-QKVLinear-Verification.sv"	// src/main/scala/QKVLinear/QKVLinear.scala:16:7
  `include "layers-LoadWeight-Verification-Assert.sv"	// src/main/scala/QKVLinear/QKVLinear.scala:16:7
`endif // not def layers_QKVLinear_Verification_Assert

