// Generated by CIRCT firtool-1.128.0
`ifndef layers_LoadWeight_Verification_Assert	// src/main/scala/QKVLinear/LoadW.scala:11:7
  `define layers_LoadWeight_Verification_Assert
  `include "layers-LoadWeight-Verification.sv"	// src/main/scala/QKVLinear/LoadW.scala:11:7
  `include "layers-WeightMem-Verification-Assert.sv"	// src/main/scala/QKVLinear/LoadW.scala:11:7
`endif // not def layers_LoadWeight_Verification_Assert

