// Generated by CIRCT firtool-1.128.0
`ifndef layers_LoadWeight_2_Verification_Assert	// src/main/scala/FFNUp/LoadW.scala:7:7
  `define layers_LoadWeight_2_Verification_Assert
  `include "layers-LoadWeight_2-Verification.sv"	// src/main/scala/FFNUp/LoadW.scala:7:7
  `include "layers-WeightMem_2-Verification-Assert.sv"	// src/main/scala/FFNUp/LoadW.scala:7:7
`endif // not def layers_LoadWeight_2_Verification_Assert

