// Generated by CIRCT firtool-1.128.0
`ifndef layers_WeightMem_1_Verification_Assert	// src/main/scala/OutLinear/WeightMem.scala:8:7
  `define layers_WeightMem_1_Verification_Assert
  `include "layers-WeightMem_1-Verification.sv"	// src/main/scala/OutLinear/WeightMem.scala:8:7
  bind WeightMem_1 WeightMem_1_Verification_Assert verification_assert ();
`endif // not def layers_WeightMem_1_Verification_Assert

