// Generated by CIRCT firtool-1.128.0
`ifndef layers_OutLinearFP32_Verification_Assert	// src/main/scala/OutLinear/OutLinearFP32.scala:9:7
  `define layers_OutLinearFP32_Verification_Assert
  `include "layers-OutLinearFP32-Verification.sv"	// src/main/scala/OutLinear/OutLinearFP32.scala:9:7
  `include "layers-LoadWeight_1-Verification-Assert.sv"	// src/main/scala/OutLinear/OutLinearFP32.scala:9:7
`endif // not def layers_OutLinearFP32_Verification_Assert

