// Generated by CIRCT firtool-1.128.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module WeightMem_3_Verification_Assert();	// src/main/scala/FFNDown/WeightMem.scala:39:9
  `ifndef SYNTHESIS	// src/main/scala/FFNDown/WeightMem.scala:39:9
    always @(posedge WeightMem_3.clock) begin	// src/main/scala/FFNDown/WeightMem.scala:8:7, :39:9
      if (~WeightMem_3.reset & WeightMem_3.legacyWrite
          & WeightMem_3.io_preload_valid) begin	// src/main/scala/FFNDown/WeightMem.scala:8:7, :9:14, :37:34, :39:{9,24}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/FFNDown/WeightMem.scala:39:9
          $error("Assertion failed: FFNDown WeightMem legacy init and preload collided\n");	// src/main/scala/FFNDown/WeightMem.scala:39:9
        if (`STOP_COND_)	// src/main/scala/FFNDown/WeightMem.scala:39:9
          $fatal;	// src/main/scala/FFNDown/WeightMem.scala:39:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


