// Generated by CIRCT firtool-1.128.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module WeightMem_Verification_Assert();	// src/main/scala/QKVLinear/WeightMem.scala:43:9
  `ifndef SYNTHESIS	// src/main/scala/QKVLinear/WeightMem.scala:43:9
    always @(posedge WeightMem.clock) begin	// src/main/scala/QKVLinear/WeightMem.scala:12:7, :43:9
      if (~WeightMem.reset & WeightMem.legacyWrite & WeightMem.io_preload_valid) begin	// src/main/scala/QKVLinear/WeightMem.scala:12:7, :13:14, :41:34, :43:{9,24}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/QKVLinear/WeightMem.scala:43:9
          $error("Assertion failed: QKV WeightMem legacy init and preload collided\n");	// src/main/scala/QKVLinear/WeightMem.scala:43:9
        if (`STOP_COND_)	// src/main/scala/QKVLinear/WeightMem.scala:43:9
          $fatal;	// src/main/scala/QKVLinear/WeightMem.scala:43:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


