package DM

import QuantCommon.Precision._

object FP32Param {
  val BATCHSIZE = Param.BATCHSIZE
  val SINGLE_QUERY_BATCH = Param.SINGLE_QUERY_BATCH
  val LOAD_VECNUM = 2
  val HEAD_VECNUM = 64
  val MAX_SEQLEN = Param.MAX_SEQLEN
  val MAX_PREFILL = Param.MAX_PREFILL
  val LOCAL_PREFILL = Param.LOCAL_PREFILL
  val TILE_SEQLEN = Param.TILE_SEQLEN
  val TILE_NUM = (MAX_SEQLEN + TILE_SEQLEN - 1) / TILE_SEQLEN
  val MULNUM = 32
  val DATAW = INT8_WIDTH
  val OUT_DATAW = FP32_WIDTH
  val OUT_WIDTH = TILE_SEQLEN * OUT_DATAW
  val MEM_DEPTH = 512
}
