// Generated by CIRCT firtool-1.128.0
`ifndef layers_GELU_Verification_Cover
  `define layers_GELU_Verification_Cover
  `include "layers-GELU-Verification.sv"
`endif // not def layers_GELU_Verification_Cover
