// Generated by CIRCT firtool-1.128.0
`ifndef layers_SiLU_Verification_Assume
  `define layers_SiLU_Verification_Assume
  `include "layers-SiLU-Verification.sv"
`endif // not def layers_SiLU_Verification_Assume
